// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC465tBv-bieXhR_RIzmEzFvNOxuz9-YUw',
    appId: '1:303389567997:web:df6704b502f348268bc794',
    messagingSenderId: '303389567997',
    projectId: 'foodly-flutter-992a8',
    authDomain: 'foodly-flutter-992a8.firebaseapp.com',
    storageBucket: 'foodly-flutter-992a8.firebasestorage.app',
    measurementId: 'G-ZYR77J4JQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjq5AXtqJQpL2ABOW8CX4P-Y76GBeFCBc',
    appId: '1:303389567997:android:64c12b7a5d9fbc5d8bc794',
    messagingSenderId: '303389567997',
    projectId: 'foodly-flutter-992a8',
    storageBucket: 'foodly-flutter-992a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUV2O11H0ilwK8HW-HKW57xAcXxDcNdI',
    appId: '1:303389567997:ios:0ebae5254a537dde8bc794',
    messagingSenderId: '303389567997',
    projectId: 'foodly-flutter-992a8',
    storageBucket: 'foodly-flutter-992a8.firebasestorage.app',
    iosClientId: '303389567997-6ihfjkhjle4874v4kbr3u5g5rg2sgk1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectAndjela',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoUV2O11H0ilwK8HW-HKW57xAcXxDcNdI',
    appId: '1:303389567997:ios:0ebae5254a537dde8bc794',
    messagingSenderId: '303389567997',
    projectId: 'foodly-flutter-992a8',
    storageBucket: 'foodly-flutter-992a8.firebasestorage.app',
    iosClientId: '303389567997-6ihfjkhjle4874v4kbr3u5g5rg2sgk1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectAndjela',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC465tBv-bieXhR_RIzmEzFvNOxuz9-YUw',
    appId: '1:303389567997:web:0d8694b222ba587c8bc794',
    messagingSenderId: '303389567997',
    projectId: 'foodly-flutter-992a8',
    authDomain: 'foodly-flutter-992a8.firebaseapp.com',
    storageBucket: 'foodly-flutter-992a8.firebasestorage.app',
    measurementId: 'G-N6XZLEB2XB',
  );
}
